apiVersion: v1
kind: Service
metadata:
  name: multipersona-service
  namespace: default
spec:
  selector:
    app: multipersona
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
